apiVersion: v1
kind: Pod
metadata:
  name: flask-pod
  namespace: task-list
  labels:
    db_type: sqlite
    app: flask_task_list
spec:
  nodeSelector:
    first_node: "true"
  containers:
  - name: flask-container
    image: flask_app
    ports:
    - containerPort: 8000
    imagePullPolicy: Never
