apiVersion: v1
kind: ReplicationController
metadata:
  name: repl-ctrl
spec:
  replicas: 3
  selector:
    app: flask_task_list
  template:
    metadata:
      name: flask-rc-app
      labels:
        app: flask_task_list
    spec:
      containers:
        - name: flask-container
          image: flask_app
          ports:
          - containerPort: 8000
          imagePullPolicy: Never
