apiVersion: v1
kind: Service
metadata:
  name: headless-service
spec:
  clusterIP: None  # forward request to all of pods
  selector:
    app: flask_task_list
  ports:
    - protocol: TCP
      port: 80
      targetPort: default-port
  type: ClusterIP  # Only inside cluster
