apiVersion: v1
kind: Service
metadata:
  name: cluster-ip-service
spec:
  selector:
    app: flask_task_list
  ports:
    - protocol: TCP
      port: 80
      targetPort: default-port
  type: ClusterIP  # Only inside cluster
