services:
  pg-server:
    image: postgres
    container_name: pg_server_02 
    volumes:
      - pg_flask_data:/var/lib/postgresql
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    restart: 
      unless-stopped
    networks:
      - inner_net
  flask-server: 
    image: flask_app
    container_name: flask_server_02
    environment:
      - DB_PASSWORD=mysecretpassword
      - DB_URI=postgresql://postgres:mysecretpassword@pg_server_02:5432/postgres
    ports:
      - 10000:8000
    depends_on:
      - pg-server
    networks:
      - inner_net
      - internet
volumes:
  pg_flask_data:
networks:
  inner_net:
    driver: bridge
    name: my_net_02
  internet:
    driver: bridge
    name: internet
